drop table if exists mpa, filmGenre, genres, likes, friends, users, films;

create table if not exists MPA (
    mpa_id integer generated by default as identity primary key,
    mpa_name varchar(255) not null unique
);

create table if not exists films(
    film_id integer generated by default as identity primary key,
    film_name varchar(255) not null,
    film_description varchar(255) not null,
    release_date date not null,
    duration integer,
    mpa_id integer
);

create table if not exists users (
    user_id integer generated by default as identity primary key,
    user_name varchar(255),
    user_login varchar(255) not null,
    email varchar(255),
    birthday date not null
);

create unique index if not exists email on USERS (email);
create unique index if not exists user_login on USERS (user_login);

create table if not exists genres (
    genre_id integer generated by default as identity primary key,
    genre_name varchar(255) not null unique
);

create table if not exists filmGenre (
PRIMARY KEY (film_id, genre_id),
    film_id integer ,
    genre_id integer,
    FOREIGN KEY (film_id) REFERENCES films(film_id),
    FOREIGN KEY (genre_id) REFERENCES genres(genre_id)
);

create table if not exists likes (
PRIMARY KEY (user_id,film_id),
    film_id integer,
    user_id integer,
        FOREIGN KEY (film_id) REFERENCES films(film_id),
            FOREIGN KEY (user_id) REFERENCES users(user_id)
);

create table if not exists friends (
    id integer generated by default as identity primary key,
    user_id integer,
    friend_id integer,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
                FOREIGN KEY (friend_id) REFERENCES users(user_id)
);